### ISSUE TITLE
How to impletate this

### ISSUE THREAD

**Issue by starredev** [zarlo/BBCodeTwigExtension#1]
Hello!

How to impletate this in the view? I already tried this: $twig->addExtension(new \zarlo\BBcode());

Cheers!

**Comment by zarlo** [comment]
$twig->addExtension(new \zarlo\BBcode());
should work and the to use it you should only need to 
{{ "some md" | bbcode }}


and have you installed it via composer

**Comment by starredev** [comment]
Thanks for the fast response!

Now i got the message;

Fatal error
Uncaught exception: 'ArgumentCountError'

Message: 'Too few arguments to function zarlo\twig\BBcode::__construct(), 0 passed in /home/admin/domains/habcms.nl/public_html/Core/View.php on line 51 and exactly 1 expected'

**Comment by zarlo** [comment]
o if you have ```new ChrisKonnertz\BBCode\BBCode()``` as the argument that should fix it

**Comment by starredev** [comment]
Youre the best! Thanks man!

**Comment by zarlo** [comment]
i have pushed an update that should remove the need for ```new ChrisKonnertz\BBCode\BBCode()```
